theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
soft-wrap.enable = true

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

